import { pgTable, uuid, text, integer, varchar, timestamp, index } from 'drizzle-orm/pg-core';
import { modelFiles } from './model-file.js';

// Thumbnails table — resized webp renditions of image files.
// Generated by ThumbnailService for each image ModelFile.
// ON DELETE CASCADE: When the source file is deleted, its thumbnails are deleted automatically.
export const thumbnails = pgTable(
  'thumbnails',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sourceFileId: uuid('source_file_id')
      .notNull()
      .references(() => modelFiles.id, { onDelete: 'cascade' }),
    // Path in managed storage: <storage_root>/thumbnails/<model_id>/<thumbnail_id>.webp
    storagePath: text('storage_path').notNull(),
    width: integer('width').notNull(),
    height: integer('height').notNull(),
    // Rendition format — always 'webp' in MVP
    format: varchar('format', { length: 20 }).notNull().default('webp'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    // Fetch all thumbnails for a source file (PresenterService: resolve thumbnail URL)
    index('thumbnails_source_file_id_idx').on(table.sourceFileId),
  ],
);

export type Thumbnail = typeof thumbnails.$inferSelect;
export type NewThumbnail = typeof thumbnails.$inferInsert;
